#!/usr/bin/env python3
"""Post-process and plot two-layer zigzag Kondo spin-correlation data.

The script expects JSON outputs generated by:
  src_kondo_two_layer_zigzag/vmps.cpp

Output naming convention consumed here:
  l0szszJperp...Jk...t2...U...Ly...Lx...D<bond_dim>.json
  l0spsm...
  l0smsp...
  l1szsz...
  l1spsm...
  l1smsp...

It builds layer-resolved S.S profiles versus |dx| and performs a finite-D
extrapolation versus 1/D for each distance.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Mapping, Sequence, Tuple

import numpy as np


Pair = Tuple[int, int]
PairData = Dict[Pair, float]
Profile = Dict[int, float]


@dataclass(frozen=True)
class CaseSpec:
    jperp: float
    jk: float
    t2: float
    u: float
    lx: int
    ly: int


def _fmt_num(val: float) -> str:
    """Match std::ostringstream default numeric formatting closely."""
    return f"{val:g}"


def build_file_postfix(spec: CaseSpec, d: int | None = None) -> str:
    """Return the filename postfix with or without trailing D token."""
    base = (
        f"Jperp{_fmt_num(spec.jperp)}"
        f"Jk{_fmt_num(spec.jk)}"
        f"t2{_fmt_num(spec.t2)}"
        f"U{_fmt_num(spec.u)}"
        f"Ly{spec.ly}"
        f"Lx{spec.lx}"
    )
    if d is None:
        return base
    return f"{base}D{d}"


def _value_to_float(raw: object) -> float:
    if isinstance(raw, (int, float)):
        return float(raw)
    if isinstance(raw, Sequence) and len(raw) == 2 and all(
        isinstance(x, (int, float)) for x in raw
    ):
        # Complex value serialized as [real, imag]; use real part.
        return float(raw[0])
    raise ValueError(f"Unsupported numeric value: {raw!r}")


def _load_pair_data(path: Path) -> PairData:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise ValueError(f"{path} does not contain a JSON list.")

    parsed: PairData = {}
    for row in raw:
        if (
            not isinstance(row, Sequence)
            or len(row) != 2
            or not isinstance(row[0], Sequence)
            or len(row[0]) != 2
        ):
            raise ValueError(f"Malformed row in {path}: {row!r}")
        i = int(row[0][0])
        j = int(row[0][1])
        parsed[(i, j)] = _value_to_float(row[1])
    return parsed


def _decode_localized_site(site: int, ly: int) -> Tuple[int, int, int]:
    """Return (x, y, layer) for localized site index in 4-site block mapping."""
    if site < 0:
        raise ValueError(f"Negative site index: {site}")
    if site % 2 == 0:
        raise ValueError(f"Expected localized (odd) site index, got even {site}")
    offset = site % 4
    if offset not in (1, 3):
        raise ValueError(f"Index {site} is odd but not a localized-site offset (1/3).")
    layer = 0 if offset == 1 else 1
    geom = site // 4
    y = geom % ly
    x = geom // ly
    return x, y, layer


def _combine_spin_components(zz: PairData, pm: PairData, mp: PairData) -> PairData:
    if zz.keys() != pm.keys() or zz.keys() != mp.keys():
        raise ValueError("Spin-correlation components have mismatched pair sets.")
    return {pair: zz[pair] + 0.5 * (pm[pair] + mp[pair]) for pair in zz}


def _profile_from_pairs(
    pairs: PairData, ly: int, expected_layer: int
) -> Profile:
    by_dx: Dict[int, List[float]] = {}
    ref_site: int | None = None

    for (s1, s2), corr in pairs.items():
        x1, _, l1 = _decode_localized_site(s1, ly)
        x2, _, l2 = _decode_localized_site(s2, ly)
        if l1 != expected_layer or l2 != expected_layer:
            raise ValueError(
                f"Found non-layer-{expected_layer} pair ({s1},{s2}) in layer {expected_layer} dataset."
            )
        if ref_site is None:
            ref_site = s1
        elif s1 != ref_site:
            raise ValueError(
                f"Expected a fixed reference site but found {ref_site} and {s1}."
            )
        dx = abs(x2 - x1)
        if dx == 0:
            continue
        by_dx.setdefault(dx, []).append(corr)

    profile: Profile = {}
    for dx, vals in by_dx.items():
        profile[dx] = float(np.mean(np.abs(vals)))
    return profile


def _prefix_path(data_dir: Path, prefix: str, spec: CaseSpec, d: int) -> Path:
    return data_dir / f"{prefix}{build_file_postfix(spec, d)}.json"


def _discover_ds_for_prefix(data_dir: Path, spec: CaseSpec, prefix: str) -> List[int]:
    token = re.escape(f"{prefix}{build_file_postfix(spec)}D")
    patt = re.compile(rf"^{token}(\d+)\.json$")
    ds: List[int] = []
    for fp in data_dir.glob(f"{prefix}{build_file_postfix(spec)}D*.json"):
        m = patt.match(fp.name)
        if m:
            ds.append(int(m.group(1)))
    return sorted(set(ds))


def find_complete_ds(data_dir: Path | str, spec: CaseSpec) -> List[int]:
    data_path = Path(data_dir)
    required_prefixes = (
        "l0szsz",
        "l0spsm",
        "l0smsp",
        "l1szsz",
        "l1spsm",
        "l1smsp",
    )

    available_sets = [
        set(_discover_ds_for_prefix(data_path, spec, prefix))
        for prefix in required_prefixes
    ]
    if not available_sets:
        return []
    common = set.intersection(*available_sets)
    return sorted(common)


def load_spin_profile_for_layer(
    data_dir: Path | str, spec: CaseSpec, d: int, layer: int
) -> Profile:
    data_path = Path(data_dir)
    if layer not in (0, 1):
        raise ValueError("layer must be 0 or 1.")

    prefix = f"l{layer}"
    zz = _load_pair_data(_prefix_path(data_path, f"{prefix}szsz", spec, d))
    pm = _load_pair_data(_prefix_path(data_path, f"{prefix}spsm", spec, d))
    mp = _load_pair_data(_prefix_path(data_path, f"{prefix}smsp", spec, d))

    sdot = _combine_spin_components(zz, pm, mp)
    return _profile_from_pairs(sdot, ly=spec.ly, expected_layer=layer)


def extrapolate_vs_inverse_d(
    points_by_d: Mapping[int, Mapping[int, float]], order: str = "linear"
) -> Profile:
    if order not in ("linear", "quadratic", "auto"):
        raise ValueError("order must be one of: linear, quadratic, auto")

    all_dx = sorted({dx for values in points_by_d.values() for dx in values})
    extrapolated: Profile = {}
    for dx in all_dx:
        dvals: List[int] = []
        yvals: List[float] = []
        for d, profile in points_by_d.items():
            if dx in profile:
                dvals.append(d)
                yvals.append(profile[dx])

        if not dvals:
            continue
        if len(dvals) == 1:
            extrapolated[dx] = float(yvals[0])
            continue

        x = np.array([1.0 / d for d in dvals], dtype=float)
        y = np.array(yvals, dtype=float)

        fit_order = 1
        if order == "quadratic":
            fit_order = 2
        elif order == "auto":
            fit_order = 2 if len(dvals) >= 4 else 1
        if fit_order == 2 and len(dvals) < 3:
            fit_order = 1

        coeff = np.polyfit(x, y, fit_order)
        extrapolated[dx] = float(np.polyval(coeff, 0.0))
    return extrapolated


def _save_profiles_csv(path: Path, profiles_by_d: Mapping[int, Profile]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["D", "dx", "corr_abs"])
        for d in sorted(profiles_by_d):
            for dx in sorted(profiles_by_d[d]):
                writer.writerow([d, dx, f"{profiles_by_d[d][dx]:.16g}"])


def _save_extrapolated_csv(path: Path, profile: Profile) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["dx", "corr_abs_extrap"])
        for dx in sorted(profile):
            writer.writerow([dx, f"{profile[dx]:.16g}"])


def _plot_layer_profiles(
    ax,
    profiles_by_d: Mapping[int, Profile],
    extrapolated: Profile,
    layer: int,
) -> None:
    colors = [
        (0.121, 0.466, 0.705),  # blue
        (0.172, 0.627, 0.172),  # green
        (0.580, 0.404, 0.741),  # purple
        (0.839, 0.152, 0.156),  # red
    ]
    marker_cycle = ["o", "s", "^", "D", "v", "P", "X", "*"]

    for idx, d in enumerate(sorted(profiles_by_d)):
        prof = profiles_by_d[d]
        xs = np.array(sorted(prof), dtype=float)
        ys = np.array([prof[k] for k in sorted(prof)], dtype=float)
        if xs.size == 0:
            continue
        ax.semilogy(
            xs,
            ys,
            marker=marker_cycle[idx % len(marker_cycle)],
            color=colors[idx % len(colors)],
            linewidth=2.0,
            markersize=6.0,
            label=f"D={d}",
        )

    if extrapolated:
        xs = np.array(sorted(extrapolated), dtype=float)
        ys = np.array([extrapolated[k] for k in sorted(extrapolated)], dtype=float)
        ax.semilogy(
            xs,
            ys,
            linestyle="--",
            color="black",
            linewidth=2.2,
            label=r"$D\to\infty$",
        )

    ax.set_xlabel(r"$\Delta x$")
    ax.set_ylabel(r"$|S\cdot S|$")
    ax.set_title(f"Layer {layer} localized spins")
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(frameon=False, fontsize=10)


def _plot_summary(
    layer0_by_d: Mapping[int, Profile],
    layer1_by_d: Mapping[int, Profile],
    extrap0: Profile,
    extrap1: Profile,
    out_path_prefix: Path,
    spec: CaseSpec,
) -> None:
    import matplotlib.pyplot as plt

    plt.rcParams.update(
        {
            "font.family": "Arial",
            "axes.linewidth": 1.5,
            "axes.labelsize": 14,
            "xtick.labelsize": 12,
            "ytick.labelsize": 12,
            "legend.fontsize": 10,
        }
    )
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.5), constrained_layout=True)
    _plot_layer_profiles(axes[0], layer0_by_d, extrap0, layer=0)
    _plot_layer_profiles(axes[1], layer1_by_d, extrap1, layer=1)
    fig.suptitle(
        (
            "Two-layer zigzag localized-spin correlation profile\n"
            + rf"$J_K={_fmt_num(spec.jk)}$, $J_\perp={_fmt_num(spec.jperp)}$, "
            + rf"$t_2={_fmt_num(spec.t2)}$, $U={_fmt_num(spec.u)}$, "
            + rf"$L_x={spec.lx}$, $L_y={spec.ly}$"
        ),
        fontsize=14,
    )
    out_path_prefix.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(Path(str(out_path_prefix) + ".pdf"), dpi=300)
    fig.savefig(Path(str(out_path_prefix) + ".png"), dpi=300)
    plt.close(fig)


def _token_for_outputs(spec: CaseSpec) -> str:
    return (
        f"Jperp{_fmt_num(spec.jperp)}"
        f"_Jk{_fmt_num(spec.jk)}"
        f"_t2{_fmt_num(spec.t2)}"
        f"_U{_fmt_num(spec.u)}"
        f"_Ly{spec.ly}_Lx{spec.lx}"
    )


def run_pipeline(
    data_dir: Path,
    out_dir: Path,
    spec: CaseSpec,
    ds: Sequence[int] | None = None,
    min_d: int | None = None,
    max_d: int | None = None,
    fit_order: str = "auto",
    make_plot: bool = True,
) -> List[int]:
    selected_ds = list(ds) if ds is not None else find_complete_ds(data_dir, spec)
    if min_d is not None:
        selected_ds = [d for d in selected_ds if d >= min_d]
    if max_d is not None:
        selected_ds = [d for d in selected_ds if d <= max_d]
    selected_ds = sorted(set(selected_ds))
    if not selected_ds:
        raise RuntimeError("No complete D sets found for the selected case.")

    layer0_by_d: Dict[int, Profile] = {}
    layer1_by_d: Dict[int, Profile] = {}
    for d in selected_ds:
        layer0_by_d[d] = load_spin_profile_for_layer(data_dir, spec, d, layer=0)
        layer1_by_d[d] = load_spin_profile_for_layer(data_dir, spec, d, layer=1)

    extrap0 = extrapolate_vs_inverse_d(layer0_by_d, order=fit_order)
    extrap1 = extrapolate_vs_inverse_d(layer1_by_d, order=fit_order)

    token = _token_for_outputs(spec)
    _save_profiles_csv(out_dir / f"layer0_profiles_{token}.csv", layer0_by_d)
    _save_profiles_csv(out_dir / f"layer1_profiles_{token}.csv", layer1_by_d)
    _save_extrapolated_csv(out_dir / f"layer0_extrapolated_{token}.csv", extrap0)
    _save_extrapolated_csv(out_dir / f"layer1_extrapolated_{token}.csv", extrap1)

    if make_plot:
        _plot_summary(
            layer0_by_d,
            layer1_by_d,
            extrap0,
            extrap1,
            out_dir / f"spincorr_profile_{token}",
            spec,
        )
    return selected_ds


def _parse_d_list(raw: str | None) -> List[int] | None:
    if raw is None:
        return None
    values: List[int] = []
    for item in raw.split(","):
        item = item.strip()
        if not item:
            continue
        values.append(int(item))
    return values


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Process/plot two-layer zigzag Kondo localized-spin correlations."
    )
    parser.add_argument("--data-dir", type=Path, default=Path("../../data"))
    parser.add_argument("--out-dir", type=Path, default=Path("./figures"))
    parser.add_argument("--jperp", type=float, required=True)
    parser.add_argument("--jk", type=float, required=True)
    parser.add_argument("--t2", type=float, required=True)
    parser.add_argument("--u", type=float, required=True)
    parser.add_argument("--lx", type=int, required=True)
    parser.add_argument("--ly", type=int, required=True)
    parser.add_argument(
        "--d-list",
        type=str,
        default=None,
        help="Optional comma-separated D list. If omitted, auto-discover complete sets.",
    )
    parser.add_argument("--min-d", type=int, default=None)
    parser.add_argument("--max-d", type=int, default=None)
    parser.add_argument(
        "--fit-order",
        choices=("auto", "linear", "quadratic"),
        default="auto",
        help="Extrapolation order versus 1/D.",
    )
    parser.add_argument("--no-plot", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    spec = CaseSpec(
        jperp=args.jperp,
        jk=args.jk,
        t2=args.t2,
        u=args.u,
        lx=args.lx,
        ly=args.ly,
    )
    ds = _parse_d_list(args.d_list)
    used = run_pipeline(
        data_dir=args.data_dir,
        out_dir=args.out_dir,
        spec=spec,
        ds=ds,
        min_d=args.min_d,
        max_d=args.max_d,
        fit_order=args.fit_order,
        make_plot=not args.no_plot,
    )
    print(f"Processed D values: {used}")
    print(f"Output directory: {args.out_dir.resolve()}")


if __name__ == "__main__":
    main()
